#!/usr/bin/env ruby
###
### CPAP (Clustering and Phylogenetic Analyzer of Proteins)
###
### Copyright: 2019-2025 (C) Yosuke Nishimura (nishimuray@jamstec.go.jp ; ynishimura@aori.u-tokyo.ac.jp)
### License: MIT license

require 'optparse'
require 'fileutils'
require 'open3'

###########################
### entry point of CPAP ###
###########################

# {{{ class CPAP
class CPAP
  VERSION  = "0.3.0"
  MODIDATE = "2025-11-18"

  ERRMSG = "\e[1;31m[error]\e[0m"
  SCCMSG = "\e[1;32m[success]\e[0m"

  # {{{ def initialize
  def initialize
    @options = {
      fin: nil,
      outdir: nil,
      ncpus: 4,
      mode: "blastp",
      dbsize: 100_000_000,
      matrix: "BLOSUM62",
      evalue: 0.01,
      min_aln_len: 40,
      min_idt: 20,
      measure: "identity",
      fphy: nil,
      fphy_as_chronogram: nil,
      clust_method: "ALL",
      overwrite: false,
      no_heatmap: false
    }

    @progname   = File.basename($0)
    @progpath   = File.absolute_path($0)
    @incmd      = "#{$0} #{ARGV.join(' ')}"
    @stime      = Time.now
    @stime_str  = @stime.strftime("%Y-%m-%d %H:%M:%S")
    @script_dir = File.dirname(@progpath)
  end
  # }}} def initialize

  # {{{ def usage
  def usage
    <<~EOF
    \e[1;35m### #{@progname} ver #{VERSION} (#{MODIDATE}) ###\e[0m

    \e[1;32m[description]\e[0m
    #{@progname} - Clustering and Phylogenetic Analyzer of Proteins/Nucleotides.
    #{@progname} generates heatmap-based visualization according to ...
      - protein similarity/%-identity using blastp/diamond/mmseqs
      - nucleotide similarity/%-identity using blastn

    #{@progname} first computes sequence identity based on BLASTp results, then converted into an identity matrix and visualizes it by a heatmap and a dendrogram.

    \e[1;32m[usage]\e[0m
    $ #{@progname} [options] <input fasta> <output dir>

    - <input fasta> should be in FASTA format.
    - <output dir> should not exist.

    \e[1;32m[dependencies]\e[0m
        - BLAST+
        - diamond
        - mmseqs2
        - ruby (ver >=3.0)
        - R (ver >=3.0)
          - R package 'gplots'     -- is used for heatmap drawing. (for install, try install.packages('gplots') in R terminal)
          - R package 'phylogram'  -- is used for generation of a newick formatted dendrogram.
          - R package 'dendextend' -- [optional] This is requried when a phylogenetic tree is NOT given (without "--phy" or "--phy-as-chronogram").
          - R package 'ape'        -- [optional] This is requried when a phylogenetic tree is given (with "--phy" or "--phy-as-chronogram").
          - R package 'phangorn'   -- [optional] This is requried when a phylogenetic tree is given (with "--phy" or "--phy-as-chronogram").

    \e[1;32m[options]\e[0m
      (general)
        -h, --help
        -v, --version
        --overwrite   (default: off) -- overwrite output directory
        --no-heatmap  (default: off) -- skip heatmap/dendrogram steps and stop after identity/similarity matrix generation
        --mode   [blastp|diamond|mmseqs|blastn] (default: blastp) -- choose blastp/diamond/mmseqs (for protein) or blastn (for nucleotide) for similarity search, currently only blastp/blastn is implemented.

      (similarity measure)
        --measure     [identity|sim-score] (default: identity) -- choice of similarity measure for heatmap generation (identity: %identity of blastp, sim-score: normalized score like Sg used in ViPTree).

      (computing)
        --ncpus       [int] (default: 4)        -- the number of cpus to use

      (blastp)
        --min-aln-len [int] (default: 20)       -- minimum amino acid length of acceptable HSP
        --min-idt     [int] (default: 20)       -- %-identity of acceptable HSP
        --dbsize      [int] (default: 100000000)
        --matrix      [str] (default: BLOSUM62)
        --evalue      [num] (default: 0.01)

      (blastn)
        --min-aln-len [int] (default: 60)       -- minimum nucleotide length of acceptable HSP
        --min-idt     [int] (default: 60)       -- %-identity of acceptable HSP
        --dbsize      [int] (default: 100000000)
        --evalue      [num] (default: 0.01)

      (provide a phylogenetic tree used as a dendrogram)
        --fphy               [str] (default: disabled) -- to provide a phylogenetic tree file (newick or nexus format). The tree is directly converted to a dendrogram of the heatmap.
        --fphy-as-chronogram [str] (default: disabled) -- to provide a phylogenetic tree file (newick or nexus format). The tree is converted to chronogram and used as a dendrogram of the heatmap.

      (clustering)
        --clust-method [ALL|average|ward.D|ward.D2|single|complete|mcquitty|median|centroid]  (default: ALL)   -- method of hclust function in R. 'ALL' performs all methods.

    \e[1;32m[output files]\e[0m
      (blastp identity mode)
        result/idt.tsv                        -- blastp %identity matrix
        result/idt-heat.<clust-method>.pdf    -- heatmap pdf file
        result/idt.ordered.<clust-method>.tsv -- blastp %identity matrix, sorted in the same order of the dendrogram.
    EOF
  end
  # }}} def usage

  # {{{ def parse_options
  def parse_options
    min_aln_len_set = false
    min_idt_set     = false

    parser = OptionParser.new do |opts|
      opts.banner = usage

      opts.on("--mode MODE", String, "choose blastp/diamond/mmseqs (for protein) or blastn (for nucleotide) for similarity search, currently onlyblastp/blastn is implemented") do |v|
        @options[:mode] = v
        case v
        when "blastp", "diamond", "mmseqs", "blastn"
          ## do nothing
        else
          warn "#{ERRMSG} --mode should be 'blastp', 'diamond', 'mmseqs', or 'blastn'."
          exit 1
        end
      end

      opts.on("--min-aln-len INT", Integer, "Minimum length of acceptable HSP") do |v|
        @options[:min_aln_len] = v
        min_aln_len_set = true
      end

      opts.on("--min-idt INT", Integer, "%-identity of acceptable HSP") do |v|
        @options[:min_idt] = v
        min_idt_set = true
      end

      opts.on("--dbsize INT", Integer, "blastp dbsize") do |v|
        @options[:dbsize] = v
      end

      opts.on("--matrix MATRIX", String, "Substitution matrix") do |v|
        @options[:matrix] = v
      end

      opts.on("--evalue NUM", Float, "blastp evalue") do |v|
        @options[:evalue] = v
      end

      opts.on("--measure MEASURE", String, "measure for similarity matrix and heatmap generation") do |v|
        @options[:measure] = v
      end

      opts.on("--fphy PATH", String, "Phylogenetic tree file (newick or nexus)") do |v|
        @options[:fphy] = v
      end

      opts.on("--fphy-as-chronogram PATH", String, "Phylogenetic tree file converted to chronogram") do |v|
        @options[:fphy_as_chronogram] = v
      end

      opts.on("--clust-method METHOD", String, "hclust method used in R") do |v|
        @options[:clust_method] = v
      end

      opts.on("--ncpus INT", Integer, "Number of cpus to use") do |v|
        @options[:ncpus] = v
      end

      opts.on("--overwrite", "Overwrite output directory") do
        @options[:overwrite] = true
      end

      opts.on("--no-heatmap", "Run only BLAST identity matrix steps (skip heatmap)") do
        @options[:no_heatmap] = true
      end

      opts.on("-h", "--help", "Show this message") do
        puts usage
        exit 0
      end

      opts.on("-v", "--version", "Show version") do
        puts VERSION
        exit 0
      end
    end

    remaining = parser.parse!(ARGV)

    case @options[:mode]
    when "blastn"
      @options[:min_aln_len] = min_aln_len_set ? @options[:min_aln_len] : 60
      @options[:min_idt]     = min_idt_set     ? @options[:min_idt]     : 60
    else
      @options[:min_aln_len] = min_aln_len_set ? @options[:min_aln_len] : 20
      @options[:min_idt]     = min_idt_set     ? @options[:min_idt]     : 20
    end

    if remaining.length < 2
      warn "#{ERRMSG} need 2 arguments"
      warn
      warn usage
      exit 1
    end

    @options[:fin]    = remaining.shift
    @options[:outdir] = remaining.shift
  end
  # }}} def parse_options

  # {{{ def validate_options
  def validate_options
    unless File.file?(@options[:fin])
      warn "#{ERRMSG} first argument should be a protein fasta file."
      exit 1
    end

    if File.exist?(@options[:outdir]) && !@options[:overwrite]
      warn "#{ERRMSG} output directory '#{@options[:outdir]}' already exists. Use --overwrite to overwrite it."
      exit 1
    end

    if @options[:fphy] && @options[:fphy_as_chronogram]
      warn "#{ERRMSG} --fphy and --fphy-as-chronogram can not be given at the same time."
      exit 1
    end
  end
  # }}} def validate_options

  # {{{ def check_dependencies
  def check_dependencies
    %w[blastp makeblastdb].each do |cmd|
      next if command_available?(cmd)
      warn "#{ERRMSG} #{cmd} (in BLAST+ package) is required but not available. Aborting."
      exit 1
    end

    unless @options[:no_heatmap]
      unless command_available?("R")
        warn "#{ERRMSG} R is required but not available. Aborting."
        exit 1
      end
    end

    if RUBY_VERSION.to_f < 3.0
      warn "#{ERRMSG} ruby (version >=3.0) is required. Aborting."
      exit 1
    end
  end
  # }}} def check_dependencies

  # {{{ def setup_logging
  def setup_logging
    @logdir  = File.join(@options[:outdir], "log")
    @logfile = File.join(@logdir, "#{@progname}.log")

    FileUtils.mkdir_p(@logdir)

    log_header = <<~EOF

    \e[1;32m===== command line\e[0m

    $ #{@incmd}

    \e[1;32m===== log file\e[0m

    #{@logfile}

    \e[1;32m===== check version: #{@progname}\e[0m

    #{VERSION}

    EOF

    File.open(@logfile, "w") { |f| f.puts log_header }
    puts log_header
  end
  # }}} def setup_logging

  # {{{ def run_rake
  def run_rake
    rakefile = File.join(@script_dir, "#{@progname}.rake")

    env_vars = {
      "dir"                  => @options[:outdir],
      "fin"                  => @options[:fin],
      "mode"                 => @options[:mode],
      "min_aln_len"          => @options[:min_aln_len].to_s,
      "min_idt"              => @options[:min_idt].to_s,
      "dbsize"               => @options[:dbsize].to_s,
      "matrix"               => @options[:matrix].to_s,
      "evalue"               => @options[:evalue].to_s,
      "measure"              => @options[:measure].to_s,
      "clust_method"         => @options[:clust_method].to_s,
      "fphy"                 => @options[:fphy].to_s,
      "fphy_as_chronogram"   => @options[:fphy_as_chronogram].to_s,
      "ncpus"                => @options[:ncpus].to_s,
      "no_heatmap"           => @options[:no_heatmap] ? "true" : ""
    }

    env_vars.each { |k, v| ENV[k] = v }

      ### [use] Open3.popen3 to capture stdout/stderr line by line
      require 'open3'
    status = nil
    begin
      open(@logfile, "a") do |fw|
        fw.sync = true
        Open3.popen3("rake -f #{rakefile} 2>&1") do |stdin, stdout, _, wait_thr|
          stdin.close
          stdout.each_line do |line|
            fw.puts line
            $stdout.print line
          end
          status = wait_thr.value.exitstatus
        end
      end

      etime     = Time.now
      etime_str = etime.strftime("%Y-%m-%d %H:%M:%S %z")

      if status == 0
        sfile = File.join(@logdir, "#{@stime_str}.#{@progname}.success")
        smsg  = "#{SCCMSG} run finished: #{etime_str}. elapsed time: #{etime - @stime} seconds."
        File.write(sfile, smsg)
        $stderr.puts smsg
      else
        efile = File.join(@logdir, "#{@stime_str}.#{@progname}.error")
        emsg  = "#{ERRMSG} run aborted: #{etime_str}. elapsed time: #{etime - @stime} seconds."
        File.write(efile, emsg)
        $stderr.puts emsg
        exit 1
      end
    rescue Interrupt
      etime     = Time.now
      etime_str = etime.strftime("%Y-%m-%d %H:%M:%S %z")

      efile = File.join(@logdir, "#{@stime_str}.#{@progname}.error")
      emsg  = "#{ERRMSG} run interrupted: #{etime_str}. elapsed time: #{etime - @stime} seconds."
      File.write(efile, emsg)
      $stderr.puts emsg
      exit 1
    end
  end
  # }}} def run_rake

  # {{{ def run
  def run
    parse_options
    validate_options
    check_dependencies
    setup_logging
    run_rake
  end
  # }}} def run

  private

  def command_available?(cmd)
    system("command -v #{cmd} >/dev/null 2>&1")
  end
end
# }}} class CPAP

if __FILE__ == $0
  CPAP.new.run
end
