name: CPAP_v0.3.0
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.4.3
  - r-gplots
  - r-phylogram
  - r-phangorn
  - r-ape
  - r-dendextend
  - ruby=3.4.5
  - blast=2.17.0
  - diamond=2.1.16
  - mmseqs2=17.b804f
